FROM node:16

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

# Entrypoint script for proper application execution
COPY ./start.sh .
RUN chmod +x ./start.sh

ENTRYPOINT ["/app/start.sh"]